/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IaRouteImport } from './routes/ia'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EvolucoesRouteImport } from './routes/evolucoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'
import { Route as FinanceiroVendasRouteImport } from './routes/financeiro.vendas'
import { Route as FinanceiroContasPagarRouteImport } from './routes/financeiro.contas-pagar'
import { Route as FinanceiroContasFinanceirasRouteImport } from './routes/financeiro.contas-financeiras'
import { Route as FinanceiroCaixaRouteImport } from './routes/financeiro.caixa'
import { Route as DashboardsOperacionalRouteImport } from './routes/dashboards.operacional'
import { Route as DashboardsGerencialRouteImport } from './routes/dashboards.gerencial'
import { Route as DashboardsCrmRouteImport } from './routes/dashboards.crm'
import { Route as CrmOportunidadesRouteImport } from './routes/crm.oportunidades'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmAtividadesRouteImport } from './routes/crm.atividades'
import { Route as AgendaOcupacaoRouteImport } from './routes/agenda.ocupacao'
import { Route as AgendaGradesRouteImport } from './routes/agenda.grades'
import { Route as PacientesIdEditarRouteImport } from './routes/pacientes.$id.editar'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucoesRoute = EvolucoesRouteImport.update({
  id: '/evolucoes',
  path: '/evolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PacientesRoute,
} as any)
const FinanceiroVendasRoute = FinanceiroVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasPagarRoute = FinanceiroContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasFinanceirasRoute =
  FinanceiroContasFinanceirasRouteImport.update({
    id: '/contas-financeiras',
    path: '/contas-financeiras',
    getParentRoute: () => FinanceiroRoute,
  } as any)
const FinanceiroCaixaRoute = FinanceiroCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => FinanceiroRoute,
} as any)
const DashboardsOperacionalRoute = DashboardsOperacionalRouteImport.update({
  id: '/dashboards/operacional',
  path: '/dashboards/operacional',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsGerencialRoute = DashboardsGerencialRouteImport.update({
  id: '/dashboards/gerencial',
  path: '/dashboards/gerencial',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsCrmRoute = DashboardsCrmRouteImport.update({
  id: '/dashboards/crm',
  path: '/dashboards/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmOportunidadesRoute = CrmOportunidadesRouteImport.update({
  id: '/crm/oportunidades',
  path: '/crm/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmAtividadesRoute = CrmAtividadesRouteImport.update({
  id: '/crm/atividades',
  path: '/crm/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaOcupacaoRoute = AgendaOcupacaoRouteImport.update({
  id: '/ocupacao',
  path: '/ocupacao',
  getParentRoute: () => AgendaRoute,
} as any)
const AgendaGradesRoute = AgendaGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AgendaRoute,
} as any)
const PacientesIdEditarRoute = PacientesIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => PacientesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/evolucoes': typeof EvolucoesRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pendencias': typeof PendenciasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sync': typeof SyncRoute
  '/agenda/grades': typeof AgendaGradesRoute
  '/agenda/ocupacao': typeof AgendaOcupacaoRoute
  '/crm/atividades': typeof CrmAtividadesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/oportunidades': typeof CrmOportunidadesRoute
  '/dashboards/crm': typeof DashboardsCrmRoute
  '/dashboards/gerencial': typeof DashboardsGerencialRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/contas-financeiras': typeof FinanceiroContasFinanceirasRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/vendas': typeof FinanceiroVendasRoute
  '/pacientes/$id': typeof PacientesIdRouteWithChildren
  '/pacientes/$id/editar': typeof PacientesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/evolucoes': typeof EvolucoesRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pendencias': typeof PendenciasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sync': typeof SyncRoute
  '/agenda/grades': typeof AgendaGradesRoute
  '/agenda/ocupacao': typeof AgendaOcupacaoRoute
  '/crm/atividades': typeof CrmAtividadesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/oportunidades': typeof CrmOportunidadesRoute
  '/dashboards/crm': typeof DashboardsCrmRoute
  '/dashboards/gerencial': typeof DashboardsGerencialRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/contas-financeiras': typeof FinanceiroContasFinanceirasRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/vendas': typeof FinanceiroVendasRoute
  '/pacientes/$id': typeof PacientesIdRouteWithChildren
  '/pacientes/$id/editar': typeof PacientesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/evolucoes': typeof EvolucoesRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pendencias': typeof PendenciasRoute
  '/relatorios': typeof RelatoriosRoute
  '/sync': typeof SyncRoute
  '/agenda/grades': typeof AgendaGradesRoute
  '/agenda/ocupacao': typeof AgendaOcupacaoRoute
  '/crm/atividades': typeof CrmAtividadesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/oportunidades': typeof CrmOportunidadesRoute
  '/dashboards/crm': typeof DashboardsCrmRoute
  '/dashboards/gerencial': typeof DashboardsGerencialRoute
  '/dashboards/operacional': typeof DashboardsOperacionalRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/contas-financeiras': typeof FinanceiroContasFinanceirasRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/vendas': typeof FinanceiroVendasRoute
  '/pacientes/$id': typeof PacientesIdRouteWithChildren
  '/pacientes/$id/editar': typeof PacientesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/dashboard'
    | '/evolucoes'
    | '/financeiro'
    | '/historico'
    | '/ia'
    | '/login'
    | '/pacientes'
    | '/pendencias'
    | '/relatorios'
    | '/sync'
    | '/agenda/grades'
    | '/agenda/ocupacao'
    | '/crm/atividades'
    | '/crm/leads'
    | '/crm/oportunidades'
    | '/dashboards/crm'
    | '/dashboards/gerencial'
    | '/dashboards/operacional'
    | '/financeiro/caixa'
    | '/financeiro/contas-financeiras'
    | '/financeiro/contas-pagar'
    | '/financeiro/vendas'
    | '/pacientes/$id'
    | '/pacientes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/dashboard'
    | '/evolucoes'
    | '/financeiro'
    | '/historico'
    | '/ia'
    | '/login'
    | '/pacientes'
    | '/pendencias'
    | '/relatorios'
    | '/sync'
    | '/agenda/grades'
    | '/agenda/ocupacao'
    | '/crm/atividades'
    | '/crm/leads'
    | '/crm/oportunidades'
    | '/dashboards/crm'
    | '/dashboards/gerencial'
    | '/dashboards/operacional'
    | '/financeiro/caixa'
    | '/financeiro/contas-financeiras'
    | '/financeiro/contas-pagar'
    | '/financeiro/vendas'
    | '/pacientes/$id'
    | '/pacientes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/dashboard'
    | '/evolucoes'
    | '/financeiro'
    | '/historico'
    | '/ia'
    | '/login'
    | '/pacientes'
    | '/pendencias'
    | '/relatorios'
    | '/sync'
    | '/agenda/grades'
    | '/agenda/ocupacao'
    | '/crm/atividades'
    | '/crm/leads'
    | '/crm/oportunidades'
    | '/dashboards/crm'
    | '/dashboards/gerencial'
    | '/dashboards/operacional'
    | '/financeiro/caixa'
    | '/financeiro/contas-financeiras'
    | '/financeiro/contas-pagar'
    | '/financeiro/vendas'
    | '/pacientes/$id'
    | '/pacientes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EvolucoesRoute: typeof EvolucoesRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  HistoricoRoute: typeof HistoricoRoute
  IaRoute: typeof IaRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  PendenciasRoute: typeof PendenciasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SyncRoute: typeof SyncRoute
  CrmAtividadesRoute: typeof CrmAtividadesRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmOportunidadesRoute: typeof CrmOportunidadesRoute
  DashboardsCrmRoute: typeof DashboardsCrmRoute
  DashboardsGerencialRoute: typeof DashboardsGerencialRoute
  DashboardsOperacionalRoute: typeof DashboardsOperacionalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucoes': {
      id: '/evolucoes'
      path: '/evolucoes'
      fullPath: '/evolucoes'
      preLoaderRoute: typeof EvolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/financeiro/vendas': {
      id: '/financeiro/vendas'
      path: '/vendas'
      fullPath: '/financeiro/vendas'
      preLoaderRoute: typeof FinanceiroVendasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas-pagar': {
      id: '/financeiro/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof FinanceiroContasPagarRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas-financeiras': {
      id: '/financeiro/contas-financeiras'
      path: '/contas-financeiras'
      fullPath: '/financeiro/contas-financeiras'
      preLoaderRoute: typeof FinanceiroContasFinanceirasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/caixa': {
      id: '/financeiro/caixa'
      path: '/caixa'
      fullPath: '/financeiro/caixa'
      preLoaderRoute: typeof FinanceiroCaixaRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/dashboards/operacional': {
      id: '/dashboards/operacional'
      path: '/dashboards/operacional'
      fullPath: '/dashboards/operacional'
      preLoaderRoute: typeof DashboardsOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/gerencial': {
      id: '/dashboards/gerencial'
      path: '/dashboards/gerencial'
      fullPath: '/dashboards/gerencial'
      preLoaderRoute: typeof DashboardsGerencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/crm': {
      id: '/dashboards/crm'
      path: '/dashboards/crm'
      fullPath: '/dashboards/crm'
      preLoaderRoute: typeof DashboardsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/oportunidades': {
      id: '/crm/oportunidades'
      path: '/crm/oportunidades'
      fullPath: '/crm/oportunidades'
      preLoaderRoute: typeof CrmOportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/atividades': {
      id: '/crm/atividades'
      path: '/crm/atividades'
      fullPath: '/crm/atividades'
      preLoaderRoute: typeof CrmAtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/ocupacao': {
      id: '/agenda/ocupacao'
      path: '/ocupacao'
      fullPath: '/agenda/ocupacao'
      preLoaderRoute: typeof AgendaOcupacaoRouteImport
      parentRoute: typeof AgendaRoute
    }
    '/agenda/grades': {
      id: '/agenda/grades'
      path: '/grades'
      fullPath: '/agenda/grades'
      preLoaderRoute: typeof AgendaGradesRouteImport
      parentRoute: typeof AgendaRoute
    }
    '/pacientes/$id/editar': {
      id: '/pacientes/$id/editar'
      path: '/editar'
      fullPath: '/pacientes/$id/editar'
      preLoaderRoute: typeof PacientesIdEditarRouteImport
      parentRoute: typeof PacientesIdRoute
    }
  }
}

interface AgendaRouteChildren {
  AgendaGradesRoute: typeof AgendaGradesRoute
  AgendaOcupacaoRoute: typeof AgendaOcupacaoRoute
}

const AgendaRouteChildren: AgendaRouteChildren = {
  AgendaGradesRoute: AgendaGradesRoute,
  AgendaOcupacaoRoute: AgendaOcupacaoRoute,
}

const AgendaRouteWithChildren =
  AgendaRoute._addFileChildren(AgendaRouteChildren)

interface FinanceiroRouteChildren {
  FinanceiroCaixaRoute: typeof FinanceiroCaixaRoute
  FinanceiroContasFinanceirasRoute: typeof FinanceiroContasFinanceirasRoute
  FinanceiroContasPagarRoute: typeof FinanceiroContasPagarRoute
  FinanceiroVendasRoute: typeof FinanceiroVendasRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroCaixaRoute: FinanceiroCaixaRoute,
  FinanceiroContasFinanceirasRoute: FinanceiroContasFinanceirasRoute,
  FinanceiroContasPagarRoute: FinanceiroContasPagarRoute,
  FinanceiroVendasRoute: FinanceiroVendasRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface PacientesIdRouteChildren {
  PacientesIdEditarRoute: typeof PacientesIdEditarRoute
}

const PacientesIdRouteChildren: PacientesIdRouteChildren = {
  PacientesIdEditarRoute: PacientesIdEditarRoute,
}

const PacientesIdRouteWithChildren = PacientesIdRoute._addFileChildren(
  PacientesIdRouteChildren,
)

interface PacientesRouteChildren {
  PacientesIdRoute: typeof PacientesIdRouteWithChildren
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesIdRoute: PacientesIdRouteWithChildren,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EvolucoesRoute: EvolucoesRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  HistoricoRoute: HistoricoRoute,
  IaRoute: IaRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRouteWithChildren,
  PendenciasRoute: PendenciasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SyncRoute: SyncRoute,
  CrmAtividadesRoute: CrmAtividadesRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmOportunidadesRoute: CrmOportunidadesRoute,
  DashboardsCrmRoute: DashboardsCrmRoute,
  DashboardsGerencialRoute: DashboardsGerencialRoute,
  DashboardsOperacionalRoute: DashboardsOperacionalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
